### ISSUE TITLE
Root Mail tests broken

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#105]
```
======================================================================
--
122 | FAIL: test_account_ready_mail_get_filtered (rootemails.RootemailsTestCase)
123 | ----------------------------------------------------------------------
124 | Traceback (most recent call last):
125 | File "/codebuild/output/src644908216/src/tests/rootemails.py", line 296, in test_account_ready_mail_get_filtered
126 | self.assertEqual(0, len(res.get('OpsItemSummaries', [])))
127 | AssertionError: 0 != 11
128 |  
129 | ======================================================================
130 | FAIL: test_welcome_mail_get_filtered (rootemails.RootemailsTestCase)
131 | ----------------------------------------------------------------------
132 | Traceback (most recent call last):
133 | File "/codebuild/output/src644908216/src/tests/rootemails.py", line 266, in test_welcome_mail_get_filtered
134 | self.assertEqual(0, len(res.get('OpsItemSummaries', [])))
135 | AssertionError: 0 != 1
136 |  
137 | ----------------------------------------------------------------------
138 | Ran 13 tests in 86.161s
```

**Comment by s0enke** [comment]
Related: https://github.com/superwerker/superwerker/issues/108
