### ISSUE TITLE
Pipeline failed: test_security_hub_cannot_be_disabled_in_member_account broken

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#115]
```

======================================================================
--
117 | ERROR: test_security_hub_cannot_be_disabled_in_member_account (tests.MyTestCase)
118 | ----------------------------------------------------------------------
119 | Traceback (most recent call last):
120 | File "/codebuild/output/src805919004/src/tests/tests.py", line 170, in test_security_hub_cannot_be_disabled_in_member_account
121 | self.assertEqual(f'An error occurred (AccessDeniedException) when calling the DisableSecurityHub operation: User: arn:aws:sts::{self.get_log_archive_account_id()}:assumed-role/SuperWerkerScpTestRole/SuperWerkerScpTest is not authorized to perform: securityhub:DisableSecurityHub on resource: arn:aws:securityhub:{scp_test_session_security_hub.region_name}:{self.get_log_archive_account_id()}:hub/default with an explicit deny', str(exception.exception))
122 | File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/botocore/client.py", line 573, in __getattr__
123 | raise AttributeError(
124 | AttributeError: 'SecurityHub' object has no attribute 'region_name'
125 |  
126 | ----------------------------------------------------------------------

```

**Comment by s0enke** [comment]
I suspect a regression here: https://github.com/superwerker/superwerker/commit/fbb3503eb82934641e0a370cf84b77103d196477#diff-6337f0a34289544e437f2604c7c78f4455c4e211183b8bf450df853e0cff9efbR170 cc @sbstjn
