### ISSUE TITLE
Pipeline failed because of IAM throttling in `test_security_hub_cannot_be_disabled_in_member_account (tests.MyTestCase)`

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#166]
```



[Container] 2021/03/01 16:15:10 Running command AWS_REGION=${SUPERWERKER_REGION} AWS_DEFAULT_REGION=${SUPERWERKER_REGION} AWS_PROFILE=test_account ACCOUNT_FACTORY_ACCOUNT_ID=$(aws --profile test_account --region ${SUPERWERKER_REGION} cloudformation describe-stacks --stack-name superwerker-pipeline-account-factory-fixture --query "Stacks[0].Outputs[?OutputKey=='AccountId'].OutputValue" --output text) python3 -munittest rootmail.py backup.py tests.py
153 | ....................E.
154 | ======================================================================
155 | ERROR: test_security_hub_cannot_be_disabled_in_member_account (tests.MyTestCase)
156 | ----------------------------------------------------------------------
157 | Traceback (most recent call last):
158 | File "/codebuild/output/src998213218/src/tests/tests.py", line 132, in test_security_hub_cannot_be_disabled_in_member_account
159 | iam.create_role(
160 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
161 | return self._make_api_call(operation_name, kwargs)
162 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
163 | raise error_class(parsed_response, operation_name)
164 | botocore.exceptions.ClientError: An error occurred (Throttling) when calling the CreateRole operation (reached max retries: 4): Rate exceeded
165 |  
166 | ----------------------------------------------------------------------
167 | Ran 22 tests in 697.550s
168 |  
169 | FAILED (errors=1)
170 |  
171 | [Container] 2021/03/01 16:26:49 Command did not exit successfully AWS_REGION=${SUPERWERKER_REGION} AWS_DEFAULT_REGION=${SUPERWERKER_REGION} AWS_PROFILE=test_account ACCOUNT_FACTORY_ACCOUNT_ID=$(aws --profile test_account --region ${SUPERWERKER_REGION} cloudformation describe-stacks --stack-name superwerker-pipeline-account-factory-fixture --query "Stacks[0].Outputs[?OutputKey=='AccountId'].OutputValue" --output text) python3 -munittest rootmail.py backup.py tests.py exit status 1
172 | [Container] 2021/03/01 16:26:49 Running command cd $CODEBUILD_SRC_DIR/tests/close-active-subaccounts
173 |  
174 | [Container] 2021/03/01 16:26:49 Running command npm i
175 | npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
176 |  
177 | > puppeteer@5.5.0 install /codebuild/output/src998213218/src/tests/close-active-subaccounts/node_modules/puppeteer
178 | > node install.js
179
```

Count: 1

Links:
 - https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/824014778649/projects/BuildAndTestProject-pV71zxUiaXub/build/BuildAndTestProject-pV71zxUiaXub%3Ae25c30da-b83f-4fbf-9c06-8d3da102266a/?region=eu-west-1

**Comment by s0enke** [comment]
https://github.com/superwerker/superwerker/commit/2da666d5e28060933454eb96fce5f5fc1648646d is a try to work around this flakiness.

**Comment by s0enke** [comment]
did not happen anymore, closing
