### ISSUE TITLE
Pipeline failed during test `test_can_change_dynamodb_backup_tags_to_none` 

### ISSUE THREAD

**Issue by s0enke** [superwerker/superwerker#167]
```
[Container] 2021/03/01 14:30:31 Running command AWS_REGION=${SUPERWERKER_REGION} AWS_DEFAULT_REGION=${SUPERWERKER_REGION} AWS_PROFILE=test_account ACCOUNT_FACTORY_ACCOUNT_ID=$(aws --profile test_account --region ${SUPERWERKER_REGION} cloudformation describe-stacks --stack-name superwerker-pipeline-account-factory-fixture --query "Stacks[0].Outputs[?OutputKey=='AccountId'].OutputValue" --output text) python3 -munittest rootmail.py backup.py tests.py
155 | .......E..............
156 | ======================================================================
157 | ERROR: test_can_change_dynamodb_backup_tags_to_none (backup.BackupTestCase)
158 | ----------------------------------------------------------------------
159 | Traceback (most recent call last):
160 | File "/codebuild/output/src113715211/src/tests/backup.py", line 82, in test_can_change_dynamodb_backup_tags_to_none
161 | ddb.tag_resource(
162 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
163 | return self._make_api_call(operation_name, kwargs)
164 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
165 | raise error_class(parsed_response, operation_name)
166 | botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the TagResource operation: Requested resource not found: ResourcArn: arn:aws:dynamodb:eu-west-1:736280444773:table/547aecd984a040e0974f9e6f379683a0 not found
167 |  
168 | ----------------------------------------------------------------------
169 | Ran 22 tests in 697.156s
170
```

Count: 1

Links:
 - https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/824014778649/projects/BuildAndTestProject-pV71zxUiaXub/build/BuildAndTestProject-pV71zxUiaXub%3A70aa0977-dc7d-481b-b582-63d55a4325f3/?region=eu-west-1

**Comment by s0enke** [comment]
did not happen anymore, closing
